### ISSUE TITLE
Error when Merging VCFs

### ISSUE THREAD

**Issue by malmarri** [DecodeGenetics/svimmer#6]
Hi,

I am trying to merge a list of VCFs of SVs using svimmer, but receive the following error:

`Traceback (most recent call last):
  File "../../../svimmer/svimmer", line 140, in <module>
    header = read_header(vcf_f)  # Read the header of the first VCF file
  File "../../../svimmer/svimmer", line 32, in read_header
    line = vcf_f.readline().decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'`

Thanks

**Comment by hannespetur** [comment]
Hi, which version of python do you have? svimmer requires python 3.4 or more recent. You can print the python version with

```sh
$ python --version
```

Best,
Hannes

**Comment by malmarri** [comment]
Hi, 

I'm using python version 3.7. 

I am trying to merge VCFs called from NUCMER alignments. Does svimmer only accept manta derived VCFs?

Thanks.

**Comment by hannespetur** [comment]
Hi, svimmer should also handle most other SV VCFs - but I don't know what NUCMER alignments are so I have probably never tested on those. I have added test data to the repo, could you try to pull the latest changes and try running svimmer on that data?

Best,
Hannes

**Comment by hannespetur** [comment]
Ah, is it possible that you have uncompressed VCF? svimmer expects bgzipped+indexed VCFs like Manta outputs. If so, just compress with bgzip and index with tabix.

Best,
Hannes

**Comment by jingydz** [comment]
The svimmer software looks like it only fits the results of merging manta output.
When I used CNVnator's output result file (converting cnv files to vcf files with cnvnator2VCF.pl) while using bgzip compression and tabix to build the index, I found that svimmer's output results were also poor.

## Command
$ cat zjj.vcf.list
0006A.delALL.vcf.gz
0032A.delALL.vcf.gz
086596D.delALL.vcf.gz
086598D.delALL.vcf.gz
086599D.delALL.vcf.gz
086600D.delALL.vcf.gz
086601D.delALL.vcf.gz
086604D.delALL.vcf.gz
086606D.delALL.vcf.gz
086620D.delALL.vcf.gz
086627D.delALL.vcf.gz
086639D.delALL.vcf.gz
086643D.delALL.vcf.gz
$ svimmer --threads 2 zjj.vcf.list chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY chrM >test.vcf

## Output
$ less test.vcf
。。。
##INFO=<ID=NUM_MERGED_SVS,Number=1,Type=Integer,Description="Number of merged SVs.">
##INFO=<ID=STDDEV_POS,Number=2,Type=Integer,Description="Std. dev of begin and end positions.">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
chr1    1       .       N       <DEL>   0       .       END=10000;SVTYPE=DEL;SVLEN=-10000;IMPRECISE;natorRD=0;natorP1=1.59373e-11;natorP2=6.0566e-44;natorP3=1.99216e-11;natorP4=2.07678e-33;natorQ0=-1;NUM_MERGED_SVS=11;STDDEV_POS=0.00,0.00

Looks like it's missing the sample information.

**Comment by hannespetur** [comment]
It´s normal that the sample information is missing. svimmer only merges SV sites, genotypes are ignored.

Best,
Hannes
